service: tick-webhook

frameworkVersion: '3'

custom:
  stage: ${opt:stage, self:provider.stage}
  settings:
    dev:
      STAGE: ${self:custom.stage}
      DYNAMODB_TABLE: tick-entries-${self:custom.stage}
      REGION: ${self:provider.region}
    prod:
      STAGE: ${self:custom.stage}
      DYNAMODB_TABLE: tick-entries-${self:custom.stage}
      REGION: ${self:provider.region}
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations


provider:
  name: aws
  runtime: nodejs16.x
  stage: dev # default stage
  region: us-east-1
  environment: ${self:custom.settings.${self:custom.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.${self:custom.stage}.DYNAMODB_TABLE}

  apiGateway:
    apiKeys:
      - basic:
          - ${self:custom.stage}-partner1
    usagePlan:
      - basic:
          throttle:
            rateLimit: 10
            burstLimit: 20

functions:
  createTickEntry:
    handler: src/lambdas/createTickEntry.handler
    events:
      - http:
          path: tick-webhook
          method: post
          cors: true
          private: true

resources:
  Resources:
    TickEntriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.settings.${self:custom.stage}.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-offline
  - serverless-dynamodb-local

