name: Deploy to Dev

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy Dev
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Get this repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: yarn install

    - name: Create env file
      run: touch env-auth.yml

    - name: Add Secrets into yml file
      run: |
        echo dev:>> env-auth.yml
        echo -e '  AUTH_TOKEN:' ${DEV_AUTH_TOKEN}>> env-auth.yml
        echo -e '  NOTION_TOKEN:' ${DEV_NOTION_TOKEN}>> env-auth.yml
        echo -e '  NOTION_DATABASE_ID:' ${DEV_NOTION_DATABASE_ID}>> env-auth.yml

      env:
        DEV_AUTH_TOKEN: ${{secrets.DEV_AUTH_TOKEN}}
        DEV_NOTION_TOKEN: ${{secrets.DEV_NOTION_TOKEN}}
        DEV_NOTION_DATABASE_ID: ${{secrets.DEV_NOTION_DATABASE_ID}}

    - name: Install Serverless global
      run: npm install -g serverless

    - name: Setup AWS Credentials
      run: serverless config credentials --provider aws --key ${{secrets.AWS_ACCESS_KEY_ID}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}

    - name: Deploy to Dev stage
      run: yarn deploy:dev
